### PR TITLE
Added improvements to Main menu & Movements

### PR DESCRIPTION
**Pull request by PrethamMuthappa**
## 👉 Checklist

> Please make sure to check off the following before submitting:

- [ ✅]  I have reviewed my submission thoroughly.
- [ ✅]  I have tested my code (if submission is related to coding) and run the game before pushing (to make sure the project compile).
- [ ✅]  I have run the JUnit tests (if submission is related to coding).
- [ ✅]  I have read the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md).

## ✍ Description of the Pull Request

> Please concisely describe the changes you have made. 

- Made changes to the main dinosaur menu by adding the dinosaur mascot in the middle
- Made changes to the Start and Quit button sizing and position
- Added mute button in Main menu to pause the start up music
- added WASD spaceship movement along with the existing Arrow movement
- Updated the control instructions for the WASD movements

Main menu Image
image

## 🔗 Issue link

> Issue reference number and link goes here e.g. 'Fixes/Closes #<issue_number>'.

- [ ] This Pull Request fixes the issue : 'Closes #'
- [✅ ] This Pull Request does not fix an issue. 

<br>

> Thanks for taking the time to fill out this Pull Request! ❤️ Thanks for contributing to this project 🦖

### CODE REVIEW

**Comment by jvondermarck** [comment]
@PrethamMuthappa Heyyyy, thank you so much for your PR !!! Great work ! Could you just check the conflicts please ? I just merged one old PR (https://github.com/dylan-power/dinosaur-exploder/pull/104). Thanks and I am sorry for the inconvenience.

**Comment by PrethamMuthappa** [comment]
@jvondermarck Heyy, I checked into the two conflicting files , I did some changes to it , I am sorry I am not much aware of the github actions and workflow , but for now I guess the conflicts have been resolved, Thanks

**Comment by jvondermarck** [comment]
image

@PrethamMuthappa Hello, thanks for resolving the conflicts, but there are many compilation errors. Could you run & test the game **before** pushing your changes please ? Thanks :)

**Comment by PrethamMuthappa** [comment]
@jvondermarck  heyy, I pulled the previous changes and fixed the errors which was showing , i tested the game and it runs as intended, I have no errors or any problem while running the game , thanks :) 

image

**Comment by jvondermarck** [comment]
Thanks so much for your contribution !!! Awesome work @PrethamMuthappa !

**Pull request merged**
