### PR TITLE
Add bomb feature

### LINKED ISSUE #121: [Feature]: add bomb
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

Adding bombs or missiles to clear the screen is a common feature  in shooting games. Our dinosaur lacks cool screen-clearing skills.

### 😍 Describe the solution you'd like

The player will have three bombs at the beginning. By pressing B, he can launch a fan-shaped barrage to kill a large number of enemies.

### 👍️ Describe alternatives you've considered

I am a github beginner and am learning how to contribute to open source projects. At present, I have written the basic logic of the bomb function, including barrage, remaining bomb count and other functions. The demonstration video is attached below.
I'm willing to address this issue if you think it's ok. I would be grateful if you assigned this to me! Thanks in advance.

https://github.com/user-attachments/assets/23f9c049-8770-4c49-96b0-7780092a2da0

### ✍ Additional context

In subsequent updates, making props drop to replenish the number of bombs is an option that can be considered.

### PR DESCRIPTION
**Pull request by ZJF39**
## 👉 Checklist

> Please make sure to check off the following before submitting:

- [x] I have reviewed my submission thoroughly.
- [x] I have tested my code (if submission is related to coding) and run the game before pushing (to make sure the project compile).
- [x] I have run the JUnit tests (if submission is related to coding).
- [x] I have read the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md).

## ✍ Description of the Pull Request

> Please concisely describe the changes you have made. 

- classes `Bomb.java` and `BombComponent.java` added
- file `bomb.png` added
- `DinosaurController.java` and `EntityType.java` and `GameEntityFactory.java` and `PauseMenu.java` modified

## 🔗 Issue link

> Issue reference number and link goes here e.g. 'Fixes/Closes #<issue_number>'.

- [X] This Pull Request fixes the issue : 'Closes #121'
- [ ] This Pull Request does not fix an issue. 

<br>

> Thanks for taking the time to fill out this Pull Request! ❤️ Thanks for contributing to this project 🦖

### CODE REVIEW

**Review by jvondermarck — APPROVED** [review]
Awesome work, thanks for the PR !! And sorry for the delay !
Just resolve the conflicts, thank you !

**Comment by ZJF39** [comment]
> Awesome work, thanks for the PR !! And sorry for the delay ! Just resolve the conflicts, thank you !

Thanks for the review! I just resolved the confict. Please let me know if there is still any bugs. :)

**Review by jvondermarck — APPROVED** [review]
Perfectttt

**Comment by jvondermarck** [comment]
Thank you so much for your contribution !!

**Pull request merged**
