### PR TITLE
Life text aligned on the left side

### LINKED ISSUE #93: [Feature]: align game info text
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

The lives and score text is not aligned on the same vertical axis.
image

### 😍 Describe the solution you'd like

It should be aligned.

### 👍️ Describe alternatives you've considered

_No response_

### ✍ Additional context

_No response_

### PR DESCRIPTION
**Pull request by diegoborbadev**
Life text aligned on the left side, this Pull Request fixes the issue : #93.

### CODE REVIEW

**Comment by jvondermarck** [comment]
Hey @diegoborbadev, thank you for your contribution ! I merged some buried PRs (I've also been a bit busy lately), and now there is merge conflict. Would you mind checking, please ? Sorry !

**Review by jvondermarck — APPROVED** [review]
Hey @diegoborbadev, thank you for your contribution !

**Comment by diegoborbadev** [comment]
> Hey @diegoborbadev, thank you for your contribution !

It was a pleasure! Just one more thing, I think issue #93 should be closed now that the pull request has been merged.

**Comment by jvondermarck** [comment]
Yes you're right, thanks @diegoborbadev !

**Pull request merged**
