### PR TITLE
[Feature]: Update the life system design

### LINKED ISSUE #60: [Feature]: Update the life system design
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

_No response_

### 😍 Describe the solution you'd like

So far, the display of the number of lives remaining looks like this:
image

it might be better to have hearts instead : 
image

Example of the above asset : 
https://github.com/AlmasB/FXGLGames/blob/master/SpaceInvaders/src/main/resources/assets/textures/life.png

### 👍️ Describe alternatives you've considered

_No response_

### ✍ Additional context

_No response_

### PR DESCRIPTION
**Pull request by singhparmeetb**
## 👉 Checklist

> Please make sure to check off the following before submitting:

- [x] I have reviewed my submission thoroughly.
- [x] I have tested my code (if submission is related to coding) and run the game before pushing (to make sure the project compile).
- [x] I have run the JUnit tests (if submission is related to coding).
- [x] I have read the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md).

## ✍ Description of the Pull Request
Added a redesigned Lives system with hearts instead of plain numbers
> Please concisely describe the changes you have made. 
- 
First of all, sorry for soo many chances, these were actually made by VS Code auto code beautifier; Hence a lot of indentation and other difference. But the major change is in only 2 files, namely

### **LifeComponent.Java** and **DinosaurController.Java**
from lines 14-63 and 29-31 respectively

The first change consists of a basic code block which checks the life variable and accordingly shows/deletes the hearts.

The edit in the second file was done so that the hearts can update even after the player is lost; Because otherwise we can still see one heart lingering around from the end menu. The code makes the game to update the score even after being lost and hence there are 0 hearts after being lost.

<image src ="https://user-images.githubusercontent.com/80666749/195941239-025552d0-966f-4175-a19d-6ac73bbc7a08.png" width="400"/>

## 🔗 Issue link

> Issue reference number and link goes here e.g. 'Fixes/Closes #60 '.

- [x] This Pull Request fixes the issue : 'Closes #'
- [ ] This Pull Request does not fix an issue. 

<br>

> Thanks for taking the time to fill out this Pull Request! ❤️ Thanks for contributing to this project 🦖

### CODE REVIEW

**Comment by singhparmeetb** [comment]
Sorry for the weird PR name💀.
 I was testing out the PR data and submitted and later saw the name

**Comment by singhparmeetb** [comment]
Again, sorry for closing this branch accidently💀
Just newbie errors

**Comment by jvondermarck** [comment]
Hi, it's awesome, great work !! Thank you. Feel free to create new issues in the project to still continue improve the game. Thanks.

**Comment by singhparmeetb** [comment]
Thank you soo much. This counts as my first ever opensource contribution and I am glad it was this game.
Once again, a huge thanks for being soo helpful and supportive!

**Pull request merged**
