### PR TITLE
Add animation of an explosion when the dinosaurs are killed

### LINKED ISSUE #47: [Feature]: Animation when the dinosaurs get killed
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

The game is called dinosaur exploder, but when you shoot on the dinosaurs, they only disappear, they don't explode

### 😍 Describe the solution you'd like

An animation using the FXGL framework of an explosion when the dinosaurs are killed

It can look like this : 
- https://github.com/AlmasB/FXGLGames/blob/master/SpaceInvaders/src/main/resources/assets/textures/explosion.png
image

### 👍️ Describe alternatives you've considered

No alternatives to total destruction I'm afraid

### ✍ Additional context

_No response_

### PR DESCRIPTION
**Pull request by QwitherY**
## 👉 Checklist

> Please make sure to check off the following before submitting:

- [x] I have reviewed my submission thoroughly.
- [x] I have tested my code (if submission is related to coding) and run the game before pushing (to make sure the project compile).
- [x] I have run the JUnit tests (if submission is related to coding).
- [x] I have read the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md).

## ✍ Description of the Pull Request

> Please concisely describe the changes you have made. 

- Add animation of an explosion when the dinosaurs are killed

## 🔗 Issue link

> Issue reference number and link goes here e.g. 'Fixes/Closes #<issue_number>'.

- [x] This Pull Request fixes the issue : 'Closes #47 '
- [ ] This Pull Request does not fix an issue. 

<br>

> Thanks for taking the time to fill out this Pull Request! ❤️ Thanks for contributing to this project 🦖

### CODE REVIEW

**Comment by QwitherY** [comment]
Because in "GameEntityFactory.java" the creation of "New Enemy BasicProjectile" and the creation of "New Green Dino" both use "EntityType.GREENDINO"，it will also have an explosion when enemy projectile collides with projectile shot by player.

**Comment by QwitherY** [comment]
Maybe you can fix it by creating "New Enemy BasicProjectile" with "EntityType.ENEMYPROJECTILE".In addition, you also need to add collision physics for "EntityType.ENEMYPROJECTILE" in DinosaurController.java .

**Comment by QwitherY** [comment]
> Because in "GameEntityFactory.java" the creation of "New Enemy BasicProjectile" and the creation of "New Green Dino" both use "EntityType.GREENDINO"，it will also have an explosion when enemy projectile collides with projectile shot by player.


https://github.com/user-attachments/assets/9bb0fe50-4e6e-4f99-8daf-b8c8dcf7ba61

**Review by jvondermarck — APPROVED** [review]
This is very awesome !! Great work, thanks for the PR and sorry for the delay !

**Pull request merged**
