### PR TITLE
Background sounds

### LINKED ISSUE #40: [Feature]: Adding sounds (SFX)
### 👉 Please confirm the following

- [X] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate features.

### 🤔 Is your proposal related to a problem?

_No response_

### 😍 Describe the solution you'd like

It would be great to add some sounds to the game : 
- ~A sound when we will be on the home screen (look at this[ issue to know if the home screen is available](https://github.com/dylan-power/dinosaur-exploder/issues/39))~
- ~A sound when we shoot (e.g search for laser shoot sounds)~
- A sound while shooting/kill a dinosaur / sound when dinosaur get hit by the laser
- ~A sound in general while playing (e.g a sound link to the space / spaceship noise...)~
- A sound when the player dies (maybe find a spaceship explosion ??)

### 👍️ Describe alternatives you've considered

Please use **OPEN SOURCE** sounds (SFX sounds : Free sounds effects). 
Be careful to not put too loud the sounds

### ✍ Additional context
You can send us a picture before doing a pull request, just so we can all agree on the sounds you choose. (Contact us on Discord, GitHub discussions, Twitter, Gmail)

### PR DESCRIPTION
**Pull request by nadia12-p**
## 👉 Checklist

> Please make sure to check off the following before submitting:

- [x] I have reviewed my submission thoroughly.
- [x] I have tested my code (if submission is related to coding) and run the game before pushing (to make sure the project compile).
- [ ] I have run the JUnit tests (if submission is related to coding).
- [x] I have read the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md).

## ✍ Description of the Pull Request

> Please concisely describe the changes you have made. 

- I've added a sound for the Home Screen, and replace the engine.wav file with the gameBackground.wav file. An additional comment I have, is that since we use the default confirmation Box I couldn't switch the sounds to the main menu when you decide to go back to the main menu after losing, maybe an issue should be open to overwrite the default confirmation box for the sounds to be able to switch back. Should I open an issue with more details? 

## 🔗 Issue link

> Issue reference number and link goes here e.g. 'Fixes/Closes #<issue_number>'.

- [x] This Pull Request fixes the issue : 'Closes #40 '
- [ ] This Pull Request does not fix an issue. 

<br>

> Thanks for taking the time to fill out this Pull Request! ❤️ Thanks for contributing to this project 🦖

### CODE REVIEW

**Comment by nadia12-p** [comment]
Hi! I was checking the files that appeared to be changed from the .idea folder, I didn't edit them but they change automatically with the IDE I'm using, at least IntelliJ modifies them automatically. I was thinking that maybe to make the PRs and code review easier, it would be better to remove this files from git, I think the IDE you use would generate them regardless of the operating system. What do you think?

**Comment by nadia12-p** [comment]
I see that the libraries from the .idea folder are already being ignored on the code, but idk why I had this issue. It didn't happen on my last PR so I'm very confused hahaha but talking about the dinosaur-exploder.iml I think we could remove that file from git, because depending on your computer operative system you're IDE will change it (I've had to restore it a couple of times lol) so yeah just a suggestion though, to make the contributions easier for different operative systems :)

**Comment by jvondermarck** [comment]
Hi @nadia12-p, first thank u for the PR it's all good, u made a great work congrats !!

If we remove the dinosaur-exploder.iml we have this issue, so I can't really remove that file from git ? : 
image

But I'm gonna remove the .idea folder though :)

**Comment by nadia12-p** [comment]
Ok I was just curious, thanks for the clarification :D

**Pull request merged**
