### PR TITLE
feat: add the ability to turn on/off sound

### PR DESCRIPTION
**Pull request by Halloween5**
## 👉 Checklist

> Please make sure to check off the following before submitting:

- [ ] I have reviewed my submission thoroughly.
- [ ] I have tested my code (if submission is related to coding) and run the game before pushing (to make sure the project compile).
- [ ] I have run the JUnit tests (if submission is related to coding).
- [ ] I have read the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md).

## ✍ Description of the Pull Request

> Please concisely describe the changes you have made. 
## What?
- I add the ability to turn off sound.
## Why?
- I noticed the project's issue on sound issues.
## How?
- I set a variable to record a soundbutton click event and control the background music. I store this variable locally.

## 🔗 Issue link

> Issue reference number and link goes here e.g. 'Fixes/Closes #<issue_number>'.

- [ ] This Pull Request fixes the issue : 'Closes #'
- [ ] This Pull Request does not fix an issue. 

<br>

> Thanks for taking the time to fill out this Pull Request! ❤️ Thanks for contributing to this project 🦖

### CODE REVIEW

**Comment by jvondermarck** [comment]
Hi @Halloween5, it would be interesting to tell the user whether the sound is on or off, so I think it would be better to display a specific icon if the sound is on or off. 

> You can download these two icons from the [Flaticon](https://www.flaticon.com/search?type=icon&search-group=all&word=sound+off&license=&color=&shape=&current_section=&author_id=&pack_id=&family_id=&style_id=&type=) website.

**Review by jvondermarck — CHANGES_REQUESTED** [review]
Hi @Halloween5, it would be interesting to tell the user whether the sound is on or off, so I think it would be better to display a specific icon if the sound is on or off.

> You can download these two icons from the [Flaticon](https://www.flaticon.com/search?type=icon&search-group=all&word=sound+off&license=&color=&shape=&current_section=&author_id=&pack_id=&family_id=&style_id=&type=) website

**Comment by jvondermarck** [comment]
Please next time, can you fill out the PR template by checking/unchecking the different boxes ?

**Comment by Halloween5** [comment]
ok, thank you

**Comment by jvondermarck** [comment]
@Halloween5 if you need any help doing that, do not hesitate to ask for help, I'm here ! ☺️

**Comment by jvondermarck** [comment]
Won't fix, too old.
Please submit another new PR if needed. Sorry.

**Pull request closed without merging**
